### ISSUE TITLE
task1

### ISSUE THREAD

**Issue by Will-Shanks** [Will-Shanks/LeedsCapstone#1]
Task 1

**Comment by kevmonsta** [comment]
We have part A complete the code to complete part A is draw.py

**Comment by kevmonsta** [comment]
We Need to Decide which Code we will be using for part B

**Comment by kevmonsta** [comment]
For Part C i think we should use a text file and not a PDF so we can keep updating it as we go.

**Comment by walterscorpionblade** [comment]
I think my code is not work perfect. Maybe we should use task1b.py.

**Comment by qisu4484** [comment]
Just upload part c txt file

**Comment by Will-Shanks** [comment]
We could consider creating a few tests for 1b
